# Generated by Django 5.1.2 on 2024-10-15 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba2', '0002_alter_deliveryservice_delivery_service_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laba2.product'),
        ),
    ]
