# Generated by Django 5.1.2 on 2024-10-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laba2', '0003_order_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
    ]
